version: 2
jobs:
  build:
    docker:
      - image: cimg/node:14.17
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - 'v1-dependencies-{{ checksum "package.json" }}'
            - v1-dependencies-
      - run: 
          name: 'Install Dependencies'
          command: 'yarn install'
      - save_cache:
          paths:
            - node_modules
          key: 'v1-dependencies-{{ checksum "package.json" }}'
      - run: 
          name: 'Test Project'
          command: 'yarn test'
      - run:
          name: 'Build Project'
          command: 'yarn build'
      - run:
          name: 'Deploy to Firebase Hosting'
          command: './node_modules/.bin/firebase deploy --token=$FIREBASE_TOKEN'